name: Build Pipeline

on:
  push:
    branches: [ "main", "Assignment2" ]
  pull_request:
    branches: [ "main", "Assignment2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: sudo apt install libxerces-c-dev

    - name: Create build directory
      run: mkdir -p ${{github.workspace}}/build

    - name: CMake Configure
      run: cmake -D CMAKE_CXX_FLAGS="-fsanitize=address" -B ${{github.workspace}}/build ${{github.workspace}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

  save_build_artifact:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      build-artifact: ${{ steps.build.outputs.build-artifact }}
    steps:
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: ${{github.workspace}}/build
