name: Test Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: ${{github.workspace}}/build
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -V
